[LinkServerInfo]
;==================================================
; Customer Settings
;==================================================
; Unique identifier for the customer's license.
CustomerLicenseId = 0

;==================================================
; Database Settings
;==================================================
; Name of the ODBC data source used to connect
; to the database managing the server data.
LinkServerODBC = MuOnline

; Optional for some setups
LinkServerUSER = 
LinkServerPASS = 

; Port number used by the Game Server (GS) to
; communicate with the Link Server.
LinkServerPort = 55950

;==================================================
; Connection Settings
;==================================================
; Maximum allowed simultaneous connections per IP address.
MaxConnectionPerIP = 0

; Maximum allowed simultaneous connections per Hardware ID (HID).
MaxConnectionPerHID = 0

;==================================================
; Common Settings
;==================================================
; Enable (1) or disable (0) MD5 encryption for communication.
MD5Encryption = 0

; Master password to bypass login authentication.
; If left empty, this feature is disabled.
; If set, this password grants access to any account.
MasterPassword =